"""fakeuser

Revision ID: 1926ca1f1d65
Revises: d9480694d971
Create Date: 2019-01-01 11:09:19.171518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1926ca1f1d65'
down_revision = 'd9480694d971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ab_user', 'group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ab_user', sa.Column('group', sa.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###
